[platformio]
default_envs = case8-ring-worker
src_dir = src

[env:case8-ring-worker]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 921600
board_build.partitions = partitions.csv
build_flags =
    -O3
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0

