
[platformio]
default_envs = link-server

[env]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

[env:link-server]
build_flags = -DBUILD_ROLE_SERVER

[env:link-client]
build_flags = -DBUILD_ROLE_CLIENT
